/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactQuery {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
  'isBestSeller' : boolean,
}
export interface ShopOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[Product], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], ShopOrder>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBestSellers' : ActorMethod<[], Array<Product>>,
  'listContactQueries' : ActorMethod<[], Array<ContactQuery>>,
  'listOrders' : ActorMethod<[], Array<ShopOrder>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'placeOrder' : ActorMethod<[ShopOrder], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedProducts' : ActorMethod<[], undefined>,
  'submitContactQuery' : ActorMethod<[ContactQuery], bigint>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];